# R for travis: see documentation at https://docs.travis-ci.com/user/languages/r

language: R
# cache: packages

addons:
  apt:
    packages:
      - python3-pip

before_install:
  - pip install --use-feature=2020-resolver --user numpy pandas mido setuptools pathlib

after_success:
  - Rscript -e 'covr::codecov()'
