# R for travis: see documentation at https://docs.travis-ci.com/user/languages/r

language: R
sudo: false
cache: packages

r:
  # - 3.4
  # - 3.5
  - 3.6
  # - 4.0
  # - devel

r_github_packages:
  - r-lib/covr
  - r-lib/pkgdown

addons:
  apt:
    update: true
    packages:
      - python3.5
      - python3-pip
      # - libgs-dev
      # - qpdf
      # - ghostscript
      - python3-setuptools
      - python-pathlib
      # - python-mido
      # - python-pandas
      # - python-numpy

before_cache: Rscript -e 'remotes::install_cran("pkgdown")'
deploy:
  provider: script
  script: Rscript -e 'pkgdown::deploy_site_github()'
  skip_cleanup: true

before_install:
  # - pip install --upgrade --user pip
  - pip3 install --user miditapyr
  # - pip install --user numpy pandas mido pathlib miditapyr

after_success:
  - Rscript -e 'covr::codecov()'
  - Rscript -e 'pkgdown::build_site()'
