# R for travis: see documentation at https://docs.travis-ci.com/user/languages/r

language: R
cache: packages

r:
  - 3.4
  - 3.5
  - 3.6
  - 4.0

addons:
  apt:
    packages:
      # - python3-pip
      - python3-setuptools
      - python-pathlib
      - python3-mido
      - python3-pandas
      - python3-numpy



before_install:
  # - pip install --upgrade --user pip
  - pip install --user miditapyr
  # - pip install --user numpy pandas mido pathlib miditapyr

after_success:
  - Rscript -e 'covr::codecov()'
