# R for travis: see documentation at https://docs.travis-ci.com/user/languages/r

language: R
cache: packages

r:
  - 3.4
  - 3.5
  - 3.6
  - 4.0

addons:
  apt:
    packages:
      - python3-pip

before_install:
  - pip3 install --user numpy pandas mido setuptools pathlib miditapyr

after_success:
  - Rscript -e 'covr::codecov()'
