### Pivot note data frame back to long format

We can transform the wide midi data back to the long format:

```{r pivot_long}
df_notes_out <-
  df_notes_wide %>%
  select(c("i_track",
           "channel", "note", "i_note"), matches("_note_o[nf]f?$")) %>%
  pivot_longer(matches("_note_o[nf]f?$"),
               names_to = c(".value", "type"),
               names_pattern = "(.+?)_(.*)") %>%
  # note events are not meta events (cf.
  # https://mido.readthedocs.io/en/latest/midi_files.html?highlight=meta#meta-messages):
  mutate(meta = FALSE)
```


### Join non note events

We can now add the non note events:

```{r join_non_note_events}
df_notes_out <-
  df_notes_out %>%
  full_join(df_meta) %>%
  full_join(df_not_notes) %>%
  # It is important to put the events in the right order:
  arrange(i_track, ticks) %>%
  group_by(i_track) %>%
  # Now we can calculate the time increments between events;
  # The first event of each track is set to 0:
  mutate(time = ticks - lag(ticks) %>% {.[1] = 0; .}) %>%
  ungroup()

df_notes_out
```

### Write midi dataframe back to a midi file

Now we can transform the data back to a dataframe of the same format as the one we got with `miditapyr$midi_to_df()`:
```{r dfc2}
dfc2 <-
  df_notes_out %>%
  # For midi export the new columns are removed:
  select(names(df)) %>%
  # When reticulate converts R dataframes to pandas, there are complications
  # with character columns containing missing values.
  # repair_reticulate_conversion = TRUE, repairs that in the miditapyr python
  # code:
  miditapyr$compact_df(repair_reticulate_conversion = TRUE)
dfc2 %>% as_tibble()
```

And we can save it back to a midi file:

```{r write_midi, eval=FALSE}
dfc2 %>%
  miditapyr$df_to_midi(ticks_per_beat,
                "test.mid")
```

